###服务启动端口号
server:
  port: 8022
###服务名称(服务注册到eureka名称)  
spring:
  application:
    name:  app-shop-zuul
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: 123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_gateway?useUnicode=true&characterEncoding=UTF-8
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


### 配置网关反向代理    
zuul:
  routes:
    api-a:
      ### 以 /api-weixin/访问转发到会员服务
      path: /api-weixin/**
      serviceId: app-ls-weixin
    api-b:
      ### 以 /api-member/访问转发到订单服务
      path: /api-member/**
      serviceId: app-ls-member
    api-c:
      ### 以 /api-pay/访问转发到订单服务
      path: /api-pay/**
      serviceId: app-ls-pay
    api-d:
      ### 以 /api-pay/访问转发到订单服务
      path: /api-spike/**
      serviceId: app-ls-spike
mayikt:
  zuul:
    swagger:
      document: 刘升电商微服务项目
      